resources:
- ../../base
patchesStrategicMerge:
- deployment.yaml
# transformers
namePrefix: production-
commonLabels:
  variant: production
  org: acmeCorporation
commonAnnotations:
  note: Hello, I am production!
